version: '3.9'

services:
  app:
    container_name: green-budget-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: green-budget-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  postgres_data:
