version: '3.9'

services:
  app:
    container_name: green-budget-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: green-budget-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # TODO: 将来的にはalembicを使ってマイグレーションを行う
      - ./docker/initdb:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres_data:
